import { languages } from 'monaco-editor';

export type Hints =
  | string[]
  | { label: string; value: string; kind: languages.CompletionItemKind }[];
/** monaco 编辑器高亮语言 */
export type EditorHighlightLanguage =
  | 'apex'
  | 'azcli'
  | 'bat'
  | 'c'
  | 'clojure'
  | 'coffeescript'
  | 'cpp'
  | 'csharp'
  | 'csp'
  | 'css'
  | 'dockerfile'
  | 'fsharp'
  | 'go'
  | 'golang'
  | 'graphql'
  | 'handlebars'
  | 'html'
  | 'ini'
  | 'java'
  | 'javascript'
  | 'json'
  | 'kotlin'
  | 'less'
  | 'lua'
  | 'markdown'
  | 'msdax'
  | 'mysql'
  | 'objective-c'
  | 'pascal'
  | 'perl'
  | 'pgsql'
  | 'php'
  | 'plaintext'
  | 'postiats'
  | 'powerquery'
  | 'powershell'
  | 'pug'
  | 'python'
  | 'r'
  | 'razor'
  | 'redis'
  | 'redshift'
  | 'ruby'
  | 'rust'
  | 'sb'
  | 'scheme'
  | 'scss'
  | 'shell'
  | 'sol'
  | 'sql'
  | 'st'
  | 'swift'
  | 'tcl'
  | 'typescript'
  | 'vb'
  | 'xml'
  | 'yaml';
